name: Build Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Rasterizer
        shell: cmd
        run: |
          cl /EHsc /std:c++17 /Iinclude main.cpp src\window.cpp src\framebuffer.cpp src\Rasterizer.cpp User32.lib Gdi32.lib /Fe:RasterizerApp.exe

      - name: Check EXE
        shell: cmd
        run: |
          dir
          dir RasterizerApp.exe

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: RasterizerApp.exe